Draft info for chunking to fix #52
EO-College/cubes-and-clouds pull request #58
Opened 2024-11-20 10:16 UTC by annefou

I started to draft the chunking section to fix #52.

2024-11-20 10:18 UTC, annefou commented
@tinaok I started to write some information about the chunking. It needs to be refined that is why I opened a draft PR.

2024-11-20 19:13 UTC, annefou commented
> Feel free to incorporate parts of https://github.com/linamaes/chunking_tutorial if you find it useful.

Great! thank you!

2024-11-25 12:13 UTC, annefou commented
@clausmichele @tinaok what do you think about having an exercise on chunking?

2025-01-05 18:16 UTC, tinaok commented
@annefou end of the chunking_introduction_snow.ipynb, it says

> Computations on big datasets can be very slow on a single computer, and to optimize its time we may need to parallelize your computations. This is what you will learn in the next episode with Dask.

Is this somewhere in this branch or it is in other branch? or it is not yet in this repo?

2025-01-05 18:43 UTC, annefou commented
We are using dask when creating the snow map but we need here to teach them how to use dask. It needs to be added in the same notebook.

2025-01-05 20:59 UTC, tinaok commented
-  2.4_exercises/chunking_introduction_snow.ipynb the setup section's package list, do we keep it? if yes we need to update the package list (for example we do not use matplotlib but use hvplot)

2025-01-05 21:22 UTC, tinaok commented
> We are using dask when creating the snow map but we need here to teach them how to use dask. It needs to be added in the same notebook.

I got the scaling_dask notebook, we can update to fit in the story.

2025-01-20 15:33 UTC, clausmichele requested changes

2025-01-20 15:38 UTC, clausmichele commented
@tinaok @annefou my review:
- Paths: please use `cubes-and-clouds/lectures/2.4_formats_and_performance/assets/` for images and auxiliary files and `cubes-and-clouds/lectures/2.4_formats_and_performance/exercises/` for the notebooks.

Lecture (markdown):
- Questions for the quiz are missing, please add a couple of questions.
- Where would you like the user to start your notebooks? The exercises are not mentioned in the lecture.

Notebooks:
- `chunking_introduction_snow.ipynb` and `scaling_dask.ipynb`:
  - there are too many things in them, remove what you already describe in the lecture. Good that you want to reuse content which was already developed, but you need to reduce the content, otherwise the users might feel overwhelmed.
  - the layout is not aligned with the other notebooks in the course.

2025-01-30 14:57 UTC, tinaok approved these changes

2025-01-30 16:05 UTC, tinaok commented on lectures/2.4_formats_and_performance/2.4_formats_and_performance.md
> +- **Data Chunking: When working with large data files or collections, it’s often impossible to load all the data into a single computer’s memory at once. In such cases, a data chunking approach can b
```suggestion
- **Data Chunking**: When working with large data files or collections, it’s often impossible to load all the data into a single computer’s memory at once. In such cases, a data chunking approach can be highly effective. By dividing the dataset into smaller chunks, the data can be processed piece by piece without exceeding the computer's memory capacity. This approach is particularly useful for managing large datasets on a single machine and can also scale to distributed computing environments, such as cloud platforms or high-performance computing systems.
```

2025-01-31 08:25 UTC, tinaok commented
@clausmichele 
other than this part

```2.4_formats_and_performance.md
> ### Cost of scalability
> 
> Direct examples of computing on a workflow
> (todo: based on actual workflow)
> 
> ### Memory consumption
> 
> limitations and 
> 
> ### Difference between platform usage and cloud directly
> 
> TODO: Is this covered already in the platform lesson? Yes
> Using platforms removes complexity and adds abstraction layers
```

And additional Questions for quiz, it is done. 
Can you please review?
thank you. 
cc: @annefou

2025-02-10 14:04 UTC, clausmichele commented
Dear @tinaok, I will review and adjust the lecture content after merging this PR. I will merge it as soon as the exercise work. However, I'm not able to run the 2.4_dask exercise. Could you please try to run it again on EOxHUB and check what's wrong?

`KilledWorker: Attempted to run task 'original-open_dataset-data-cd29d5b278197526d3ac886995ecec09' on 4 different workers, but all those workers died while running it. The last worker that attempt to run the task was tcp://127.0.0.1:36793. Inspecting worker logs is often a good next step to diagnose what went wrong. For more information see https://distributed.dask.org/en/stable/killed.html.`

@jzvolensky could you also confirm you get the same error for that notebook? You need to run the 2.4_chunking first to generate the required data.

2025-02-10 14:24 UTC, jzvolensky commented
@clausmichele to confirm:

- Bigger Pangeo Instance + pangeo kernel

- running the `chunking` branch, https://github.com/annefou/cubes-and-clouds/tree/chunking

- first running 24_chunking and then 24_dask 

I did manage to run the notebook but near the end

```python
snow_cloud.to_zarr('snow_cloud.zarr',mode='w')
```
you get a billion division by 0 warnings which are not very nice

2025-02-11 08:01 UTC, merged