Draft validation notebook for pangeo
EO-College/cubes-and-clouds pull request #60
Opened 2024-11-20 20:45 UTC by annefou

Related to #44 
@tinaok  I just started the draft; still need some work to finalise it.

2024-11-30 20:10 UTC, annefou commented
- Added  Pangeo notebooks for 2.3_data_access/exercises/_alternatives
- Added Pangeo notebook for 3.1_data_processing/3.1_exercises/_alternatives/31_data_processing_pangeo.ipynb
- added 3.2_validation/3.2_exercises/32_validation_pangeo.ipynb
- drafted 3.3_data_sharing/3.3_exercises/_alternatives/33_data_sharing_pangeo.ipynb (create COG file but stac item, etc. need to be added)

2025-01-08 10:18 UTC, clausmichele commented
Hi Anne, I noticed you removed the "draft" from title. Is the content finalized? Can we review it?

2025-01-08 10:41 UTC, annefou commented
> Hi Anne, I noticed you removed the "draft" from title. Is the content finalized? Can we review it?

Yes, I think the review can start. There is a few things to discuss but most of the notebooks are ready to be reviewed.

2025-01-09 10:36 UTC, clausmichele commented
The Pangeo exercises need to be integrated in the lecture https://github.com/EO-College/cubes-and-clouds/blob/main/lectures/2.3_data_access/2.3_data_access.md 
@annefou @tinaok please go through the lecture and propose how to introduce the Pangeo ecosystem, since now the lecture mentions openEO only.

2025-01-10 22:00 UTC, annefou commented
- merged the two utility Python scripts into a single one

2025-01-13 14:02 UTC, clausmichele commented
pangeo_data_access_filter.ipynb :
- If you remove the `Z` from the datetime, this warning will also disappear:
- ![image](https://github.com/user-attachments/assets/ff5c5294-b6a4-421c-aa01-8f4dda38422d)

2025-01-13 15:28 UTC, clausmichele commented
pangeo_data_access_reduce.ipynb : check the text, there are still mentions to the openEO processes `reduce_dimension` and `reduce_spatial`. Moreover, in your case the bands dimension is called `band`, singular.

2025-01-13 15:51 UTC, clausmichele commented
31_data_processing_pangeo.ipynb : 
- hvplot and holoviews are not in the [env](https://github.com/EO-College/cubes-and-clouds/blob/main/environment.yml) file. Should we create separate files with the environments, used on EOxHUB and not on GitHub?
-  check the text
![image](https://github.com/user-attachments/assets/8803d6b2-0f17-45a0-bf52-148b3442b8ca)
- in the `reduce` notebook you use the `.load()` method instead of `.compute()`, either explain both or keep `compute` only to avoid misunderstandings.
- The correct way to write is `rioxarray` not `RioXarray`, without uppercases, see https://zenodo.org/records/14056523
- Typos: scr instead of scl, th instead of the 
![image](https://github.com/user-attachments/assets/a3d37f69-28b3-445c-a14b-14ddb0ab6259)
- Other typos: 
![image](https://github.com/user-attachments/assets/f9a4fdd8-85df-4e0e-b383-29055d3d4983)

2025-01-18 16:15 UTC, annefou commented
> pangeo_data_access_aggregate.ipynb

I do not see any errors with `pangeo_data_access_aggregate.ipynb`  but I am running it on EOX with the `cubes-and-clouds-pangeo` kernel.

2025-01-18 19:54 UTC, annefou commented
> 31_data_processing_pangeo.ipynb :

We can use the new environment with more resources. It helps.

2025-01-20 08:37 UTC, clausmichele commented
> > pangeo_data_access_aggregate.ipynb
> 
> I do not see any errors with `pangeo_data_access_aggregate.ipynb` but I am running it on EOX with the `cubes-and-clouds-pangeo` kernel.

Could you share the environment file of that kernel? I will test again on EOxHUB.

2025-01-20 08:52 UTC, clausmichele commented
> To dos:
> 
>     * The Pangeo exercises need to be integrated in the lecture https://github.com/EO-College/cubes-and-clouds/blob/main/lectures/2.3_data_access/2.3_data_access.md @annefou @tinaok please go through the lecture and propose how to introduce the Pangeo ecosystem, since now the lecture mentions openEO only.

@annefou @tinaok this is not yet available in this PR, could you please work on it?

2025-01-27 08:11 UTC, Schpidi commented
> I don't have it available on EOxHUB, @Schpidi could you let me, @jzvolensky and @jonas-eberle have access to the same "bigger" environment?

@clausmichele I added @jonas-eberle and you but I' afraid I don't find @jzvolensky. Which email are you using to access EOxHub @jzvolensky?

2025-01-27 09:42 UTC, clausmichele requested changes

2025-01-27 09:42 UTC, clausmichele commented on lectures/2.3_data_access/2.3_data_access.md
> +> Figure: Datacube spatial resampling (up and down): Downsampling: The resulting tiles have a lower spatial resolution than the input tiles. Upsampling: The resulting tiles have a higher spatial reso
same as above, reference doesn't belong to image caption.

2025-01-27 09:42 UTC, clausmichele commented on lectures/2.3_data_access/2.3_data_access.md
> +> Figure: Datacube spatial aggregation: A line and a polygon are selected from the original example tiles. The pixels covered by these geometries are aggregated and the result consists no longer of i
same as above, reference doesn't belong to image caption.

2025-01-27 09:42 UTC, clausmichele commented on lectures/2.3_data_access/2.3_data_access.md
> +### The need for a standarized API in EO cloud processing
This should be removed, leftover.

2025-01-27 09:42 UTC, clausmichele commented on lectures/2.3_data_access/2.3_data_access.md
> +Pangeo - An Open-Source Ecosystem for Cloud-Based Data Analysis
Probably this is the title that has to replace the previous one.

2025-01-27 09:42 UTC, clausmichele commented on lectures/2.3_data_access/2.3_data_access.md
> +The need for an open-source ecosystem in cloud-based data analysis
Is this a subtitle? I think so, check the formatting otherwise the rendered markdown is not meaningful.

2025-01-27 09:42 UTC, clausmichele commented on lectures/2.3_data_access/2.3_data_access.md
> +- [xarray (2022).](https://docs.xarray.dev)
Should we use the Zenodo with its DOI for citation? https://zenodo.org/records/14623571

like:

Hoyer, S., Roos, M., Joseph, H., Magin, J., Cherian, D., Fitzgerald, C., Hauser, M., Fujii, K., Maussion, F., Imperiale, G., Clark, S., Kleeman, A., Nicholas, T., Kluyver, T., Westling, J., Munroe, J., Amici, A., Barghini, A., Banihirwe, A., … Littlejohns, O. (2025). xarray (v2025.01.1). Zenodo. https://doi.org/10.5281/zenodo.14623571

2025-01-27 09:42 UTC, clausmichele commented on lectures/2.3_data_access/2.3_data_access.md
> +- |dask](https://www.dask.org): For distributed computing, enabling parallel processing of large datasets.
```suggestion
- [dask](https://www.dask.org): For distributed computing, enabling parallel processing of large datasets.
```

2025-01-27 09:42 UTC, clausmichele commented on lectures/2.3_data_access/2.3_data_access.md
> +- **Simplicity*: Pangeo leverages widely-used Python libraries like xarray, dask, and zarr to provide easy-to-use tools for processing and analyzing large, multidimensional datasets. The aim is to ma
```suggestion
- **Simplicity**: Pangeo leverages widely-used Python libraries like xarray, dask, and zarr to provide easy-to-use tools for processing and analyzing large, multidimensional datasets. The aim is to make working with large volumes of geospatial data as simple as possible, while integrating seamlessly into existing workflows.
```

2025-01-27 09:42 UTC, clausmichele commented on lectures/2.3_data_access/2.3_data_access.md
> +A spatial aggregation (e.g. with openEO [`aggregate_spatial`](https://processes.openeo.org/#aggregate_spatial) or with Pangeo [GroupBy](https://docs.xarray.dev/en/stable/user-guide/groupby.html]) wor
```suggestion
A spatial aggregation (e.g. with openEO [`aggregate_spatial`](https://processes.openeo.org/#aggregate_spatial) or with Pangeo [GroupBy](https://docs.xarray.dev/en/stable/user-guide/groupby.html)) works in a similar manner. Polygons, lines and points can be selected for grouping. Their spatial dimension is then reduced by a given process and thus, a vector cube is returned. The vector cube then has dimensions containing features, attributes and time. In the graphic below, the grouping is only shown for the first timestep.
```

2025-01-27 09:42 UTC, clausmichele commented on lectures/2.3_data_access/2.3_data_access.md
> +With the Pangeo ecosystem and `xarray`, you can use [`resample`](https://docs.xarray.dev/en/stable/generated/xarray.Dataset.resample.html) or [`coarsen`](https://docs.xarray.dev/en/stable/generated/x
```suggestion
With the Pangeo ecosystem and `xarray`, you can use [`resample`](https://docs.xarray.dev/en/stable/generated/xarray.Dataset.resample.html) or [`coarsen`](https://docs.xarray.dev/en/stable/generated/xarray.Dataset.coarsen.html).
```

2025-01-27 09:42 UTC, clausmichele commented on lectures/2.3_data_access/2.3_data_access.md
> +Loading data with openEO: What is the difference between using an openEO remote back-end and openEO Python Client-Side-Processing? Tick what is correct. *Answer in exercises: 23_data_access_lazy_load
```suggestion
Loading data with openEO: What is the difference between using an openEO remote back-end and openEO Python Client-Side-Processing? Tick what is correct. *Answer in exercise: 23_data_access_lazy_loading.ipynb* 
```

2025-01-27 09:42 UTC, clausmichele commented on lectures/2.3_data_access/2.3_data_access.md
> +*Answer in exercises: pangeo_data_access_lazy_loading.ipynb*
```suggestion
*Answer in exercise: pangeo_data_access_lazy_loading.ipynb*
```

2025-01-27 09:42 UTC, clausmichele commented on lectures/2.3_data_access/2.3_data_access.md
> +[[x]] Remote datasets in Pangeo can be accessed lazily, meaning they are only loaded when needed
```suggestion
    [[ ]] You need a cloud account to access both remote and local data
    [[x]] Pangeo allows direct access to cloud-based datasets without needing to download them first
    [[x]] Processing data locally in Pangeo does not require cloud access
    [[ ]] Pangeo local processing requires an internet connection for all data access
    [[x]] Remote datasets in Pangeo can be accessed lazily, meaning they are only loaded when needed
```

2025-01-27 09:42 UTC, clausmichele commented on lectures/2.3_data_access/2.3_data_access.md
> +Loading: What are the dimension names of the loaded datacube? *Answer in exercise: 23_data_access_lazy_loading.ipynb and pangeo_access_lazy_loading.pynb'*
```suggestion
Loading: What are the dimension names of the loaded datacube? *Answer in exercises: 23_data_access_lazy_loading.ipynb and pangeo_access_lazy_loading.pynb'*
```

2025-01-27 09:42 UTC, clausmichele commented on lectures/2.3_data_access/2.3_data_access.md
> +Filtering: How many time steps are left after filtering temporally 2022-05-10, 2022-06-30? *Answer in exercise: 23_data_access_filter.ipynb and pangeo_data_access_filter.ipynb*
```suggestion
Filtering: How many time steps are left after filtering temporally 2022-05-10, 2022-06-30? *Answer in exercises: 23_data_access_filter.ipynb and pangeo_data_access_filter.ipynb*
```

2025-01-27 09:42 UTC, clausmichele commented on lectures/2.3_data_access/2.3_data_access.md
> +[[ ]] openEO is better suited for cloud-native operations, while Pangeo offers more customizable data workflows using local compute resources
Not sure if we should mark this as correct or not! We can discuss about it.

2025-01-27 09:42 UTC, clausmichele commented on lectures/2.3_data_access/2.3_data_access.md
> +[[ ]] openEO is better suited for cloud-native operations, while Pangeo offers more customizable data workflows using local compute resources
```suggestion
    [[ ]] Pangeo requires users to write custom code for all data operations like filtering and resampling
    [[x]] Pangeo integrates with powerful libraries like xarray and dask, allowing for efficient selection, filtering, and resampling of large datasets in parallel
    [[ ]] openEO supports filtering and resampling only through remote back-end processing
    [[x]] Pangeo allows local processing of large datasets, providing more flexibility in selecting and transforming data
    [[ ]] openEO is better suited for cloud-native operations, while Pangeo offers more customizable data workflows using local compute resources
```

2025-01-27 10:02 UTC, clausmichele commented on lectures/2.3_data_access/exercises/_alternatives/pangeo_data_access_reduce.ipynb
> +{
<p><code>band</code> instead of  <code>bands</code></p>
<br/>

 _Reply via <a href='https://app.reviewnb.com/EO-College/cubes-and-clouds/pull/60/discussion/'>ReviewNB</a>_ <div id='ReviewNBCommentContext-DoNotDelete' style='display:none' data-state='OPEN' data-cellIndex='14'/>

2025-01-27 10:02 UTC, clausmichele commented on lectures/3.1_data_processing/3.1_exercises/_alternatives/31_data_processing_pangeo.ipynb
> +{
<p>Wrong cell type, should be code instead of raw..</p>
<br/>

 _Reply via <a href='https://app.reviewnb.com/EO-College/cubes-and-clouds/pull/60/discussion/'>ReviewNB</a>_ <div id='ReviewNBCommentContext-DoNotDelete' style='display:none' data-state='OPEN' data-cellIndex='28'/>

2025-01-27 10:02 UTC, clausmichele commented on lectures/3.1_data_processing/3.1_exercises/_alternatives/31_data_processing_pangeo.ipynb
> +{
<p>Fix typo. it's <code>scl</code> instead of <code>scr</code>   <span class="ql-cursor">﻿</span></p>
<br/>

 _Reply via <a href='https://app.reviewnb.com/EO-College/cubes-and-clouds/pull/60/discussion/'>ReviewNB</a>_ <div id='ReviewNBCommentContext-DoNotDelete' style='display:none' data-state='OPEN' data-cellIndex='51'/>

2025-01-27 10:11 UTC, annefou commented on lectures/3.1_data_processing/3.1_exercises/_alternatives/31_data_processing_pangeo.ipynb
> +{
<p>Which one? I don't see it here.</p>

2025-01-27 10:17 UTC, annefou commented on lectures/2.3_data_access/2.3_data_access.md
> +### The need for a standarized API in EO cloud processing
Sorry, I don't understand what needs to be removed.

2025-01-27 10:24 UTC, annefou commented on lectures/2.3_data_access/2.3_data_access.md
> +> Figure: Datacube filtering: From the datacube 4 by 3 grid, arrows depict what happens if the grid is filtered. Temporal filtering results in data for one timestep with all four bands, filtering ban
I got it! Thank you!

2025-01-27 11:10 UTC, clausmichele commented on lectures/2.3_data_access/2.3_data_access.md
> +Pangeo - An Open-Source Ecosystem for Cloud-Based Data Analysis
Duplicate

2025-01-27 11:10 UTC, clausmichele commented on lectures/2.3_data_access/2.3_data_access.md
> +### The need for a standarized API in EO cloud processing
The subtitle: `### The need for a standarized API in EO cloud processing` comes from the openEO part, it doesn't apply here. See my following comments, it has to be replaced with `The need for an open-source ecosystem in cloud-based data analysis`

2025-01-27 11:27 UTC, annefou commented on lectures/2.3_data_access/2.3_data_access.md
> +### The need for a standarized API in EO cloud processing
Yes! I got it! Thank you!

2025-01-27 11:29 UTC, annefou commented
@clausmichele  Thank you so much for your detailed comments. I believe I’ve implemented all your suggestions and hope I haven’t missed anything. Many thanks again!

2025-01-28 09:16 UTC, jzvolensky commented
Hi,

I ran the notebooks and here is some stuff I found:

### 2.3 Data Access Filter

OpenEO reference
```
To slice along the spatial dimensions the data collection with openEO
```

### 2.3 Data Access Reduce

OpenEO reference
```
For instance, the [NDVI](https://en.wikipedia.org/wiki/Normalized_difference_vegetation_index) formula can be expressed using a reduce_dimension process over the band dimension:
```

### 3.1 Processing

In the CP the paths need to be adjusted due to the _alternate directory (don’t know where the final one will live)

```
!cp -r $DATA_PATH../31_results/ .
!cp -r $DATA_PATH../31_data/ .
```

Small suggestion to maybe have a check in the beginning if a dask cluster is already running and kill it or restart. This prevents spawning multiple ones and potential issues associated with it.

### 3.2 Validation

Need to add rio-stac-0.10.1 to the pangeo kernel due to an import error

```
We extract the SCA value of our data cube at the buffered station locations. Therefore we use the process aggregate_spatial() with the aggregation method median()
```

```
for idx,r in catchment_stations_gpd_utm32[["Name"]].drop_duplicates().iterrows():
    print(idx, r["Name"])
    x[idx].to_csv("32_results/snowmap_pangeo/" + r["Name"] + ".csv")
```

QOL if the directory doesn’t exist please create it automatically to prevent errors.

Close to the end there are a lot of warnings for division by 0, perhaps these could be surpressed somehow as it does not look so good.

### 3.3 Data sharing

In the beginning where you need to click on a map:
```
Error displaying widget: model not found
```

Looking for a fix but nothing I found so far helped.

@annefou @clausmichele

2025-01-28 13:32 UTC, jzvolensky commented
@clausmichele @annefou 

Another thought. I think the new Pangeo notebooks also need to be introduced and mentioned in the lecture contents as well as some quiz questions specific for Pangeo.

2025-01-29 10:41 UTC, annefou commented
For 3.2 Validation
I did not get an import error. I am wondering if we all use the same image.

2025-02-03 13:25 UTC, clausmichele commented
I will merge this PR now, we will open a new one to fix the latest things.

2025-02-03 13:25 UTC, merged